.TH MAN-PAGES 1 2010-10-24 "Fsset" "Fassets man page"


.SH NAME
     Fasset - Farm ASSEssment Tool

.SH SYNOPSIS
     Fasset

.SH DESCRIPTION
     FASSET is a whole-farm dynamic model, which can be used as a tool to evaluate consequences of changes in regulations, management, prices and subsidies on a range of indicators for sustainability at the farm level, e.g. farm profitability, production, nitrogen losses, energy consumption and greenhouse gas emissions.

     

.B AUTHOR
     Bjørn Molt Petersen, Mette Lægdsmand, Nicholas John Hutchings and more

