svn rename PRODUCTS.DAT products.dat
svn rename PER_CRPR.DAT per_crpr.dat
svn rename OPERATIO.DAT operatio.dat
svn rename TECHEQP.DAT techeqp.dat
svn rename PER_TECH.DAT per_tech.dat
svn rename LABPERID.DAT labperid.dat
svn rename LEGISLAT.DAT legislat.dat
svn rename fields.f02 Fields.f02
svn rename fields.f03 Fields.f03
svn rename fields.f04 Fields.f04
svn rename fields.f05 Fields.f05
svn rename fields.f06 Fields.f06
svn rename fields.f07 Fields.f07
svn rename fields.f08 Fields.f08
svn rename Fields.dat fields.dat
